### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by bojanbizjak** [SofianChouaib/alwan#3]
An error occurs when: inputs: { hex: **false**, rgb: **false**, hsl: **false** }

![Screenshot 2023-03-09 at 10 28 11](https://user-images.githubusercontent.com/12731463/223980691-6e595f6a-5163-431d-ac97-7ad9b6ced8b5.png)

**Comment by SofianChouaib** [comment]
Fixed the issue, thank you for the feeback.
